-- MySQL Script generated by MySQL Workbench
-- Wed 06 Nov 2019 07:44:04 PM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema schooldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema schooldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `schooldb` ;
USE `schooldb` ;

-- -----------------------------------------------------
-- Table `schooldb`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schooldb`.`students` ;

CREATE TABLE IF NOT EXISTS `schooldb`.`students` (
  `sid` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schooldb`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schooldb`.`courses` ;

CREATE TABLE IF NOT EXISTS `schooldb`.`courses` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`course_id`),
  UNIQUE INDEX `course_name_UNIQUE` (`course_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schooldb`.`course_enrollments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schooldb`.`course_enrollments` ;

CREATE TABLE IF NOT EXISTS `schooldb`.`course_enrollments` (
  `sid` INT NOT NULL,
  `course_id` INT NOT NULL,
  INDEX `fk_course_enrollments_sid_idx` (`sid` ASC) VISIBLE,
  INDEX `fk_course_enrollments_cid_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_enrollments_sid`
    FOREIGN KEY (`sid`)
    REFERENCES `schooldb`.`students` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_enrollments_cid`
    FOREIGN KEY (`course_id`)
    REFERENCES `schooldb`.`courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schooldb`.`course_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schooldb`.`course_schedule` ;

CREATE TABLE IF NOT EXISTS `schooldb`.`course_schedule` (
  `course_id` INT NOT NULL,
  `day_of_week` ENUM("M", "Tu", "W", "Th", "F") NOT NULL,
  `time` TIME NOT NULL,
  PRIMARY KEY (`course_id`, `day_of_week`),
  CONSTRAINT `fk_course_schedule_cid`
    FOREIGN KEY (`course_id`)
    REFERENCES `schooldb`.`courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
