-- MySQL Script generated by MySQL Workbench
-- Thu 31 Oct 2019 05:43:15 PM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ch10_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ch10_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ch10_1` ;
-- -----------------------------------------------------
-- Schema ch10-2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ch10-2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ch10-2` ;
-- -----------------------------------------------------
-- Schema ch10-3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ch10-3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ch10-3` ;
USE `ch10_1` ;

-- -----------------------------------------------------
-- Table `ch10_1`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ch10_1`.`categories` (
  `category_name` VARCHAR(45) NOT NULL,
  `category_desc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ch10_1`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ch10_1`.`products` (
  `product_name` VARCHAR(45) NOT NULL,
  `product_desc` VARCHAR(45) NOT NULL,
  `price` DECIMAL NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`product_name`),
  INDEX `fk_products_1_idx` (`category` ASC) VISIBLE,
  CONSTRAINT `fk_products_1`
    FOREIGN KEY (`category`)
    REFERENCES `ch10_1`.`categories` (`category_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `ch10-2` ;

-- -----------------------------------------------------
-- Table `ch10-2`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ch10-2`.`countries` (
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`state`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ch10-2`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ch10-2`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ch10-2`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ch10-2`.`addresses` (
  `customer_id` INT NOT NULL,
  `address_no` INT NOT NULL,
  `address_type` ENUM('default_billing', 'default_shipping') NULL,
  `street_address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `postal` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `address_no`),
  INDEX `fk_addresses_2_idx` (`state` ASC) VISIBLE,
  CONSTRAINT `fk_addresses_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `ch10-2`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_addresses_2`
    FOREIGN KEY (`state`)
    REFERENCES `ch10-2`.`countries` (`state`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `ch10-3` ;

-- -----------------------------------------------------
-- Table `ch10-3`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ch10-3`.`groups` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ch10-3`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ch10-3`.`members` (
  `member_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`member_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ch10-3`.`memberships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ch10-3`.`memberships` (
  `member_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  INDEX `fk_memberships_1_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_memberships_2_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_memberships_1`
    FOREIGN KEY (`member_id`)
    REFERENCES `ch10-3`.`members` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_memberships_2`
    FOREIGN KEY (`group_id`)
    REFERENCES `ch10-3`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
